import { Router } from 'express';
import controller from '#controllers/user-dashboard.controller';
import rosterController from '#controllers/group-rosters.controller';
import authMiddleware from '#middlewares/auth.middleware';
import { allowRoles } from '#middlewares/role.middleware';

const router = Router();
router.use(authMiddleware, allowRoles('ADMIN', 'SUPER_ADMIN', 'administrator'));
router.get('/overview', controller.overview);
router.get('/group-analytics', controller.groupAnalytics);
router.get('/access-matrix', controller.accessMatrix);
router.patch('/access-matrix/:levelId/:sectionCode', controller.updateAccess);
router.get('/access-resources', controller.resourceAccessRules);
router.patch('/access-resources/:levelId/:resourceType/:resourceKey', controller.updateResourceAccess);
router.patch('/accounts/:id', controller.updateAccount);
router.patch('/official/:id', controller.updateOfficial);
router.post('/rosters', controller.createGroup);
router.patch('/rosters/:id', controller.updateGroup);
router.delete('/rosters/:id', controller.removeGroup);
router.post('/official/:id/groups/:groupId', controller.assignGroup);
router.delete('/official/:id/groups/:groupId', controller.removeFromGroup);
router.post('/central-base/imports', rosterController.importCentral);
router.get('/central-base/history', rosterController.centralHistory);
router.post('/rosters/:groupId/imports', rosterController.importRoster);
router.get('/rosters/:groupId/current', rosterController.current);
router.get('/rosters/:groupId/history', rosterController.history);
router.post('/rosters/:groupId/imports/:importId/restore', rosterController.restore);
router.post('/rosters/:groupId/actions', rosterController.bulkAction);
export default router;
