/**
 * Catalogo de entidades administrables: es la configuracion que hace generico al
 * panel.
 *
 * Cada entrada declara el titulo, el microservicio, la ruta del recurso, el tipo
 * de identificador y los campos del formulario. `ResourcePage` no sabe nada de
 * ninguna entidad: lo lee todo de aqui, asi que anadir una tabla al panel es
 * anadir una entrada.
 *
 * Los campos son tuplas `[clave, etiqueta, tipo, opciones]`. Solo los **cuatro
 * primeros** se muestran como columnas de la tabla; el resto aparece unicamente
 * en el formulario.
 *
 * `idType: 'uuid'` hace que el identificador se genere en el cliente al crear;
 * `'number'` deja que lo asigne la base de datos.
 *
 * @see pages/shared/ResourcePage.jsx Pantalla que lo consume.
 */
export const resources = {
  courses: { title:'Cursos', singular:'curso', service:'academia', path:'courses', idType:'number', fields:[['slug','Slug','text'],['title','Título','text'],['summary','Resumen','textarea'],['description','Descripción','textarea'],['category','Categoría','text'],['status','Estado','select', ['published','draft','archived']],['image','Imagen URL','text']] },
  lessons: { title:'Lecciones', singular:'lección', service:'academia', path:'lessons', idType:'number', fields:[['course_id','ID de curso','number'],['number','Número','number'],['title','Título','text'],['summary','Resumen','textarea']] },
  enrollments: { title:'Inscripciones', singular:'inscripción', service:'academia', path:'enrollments', idType:'uuid', fields:[['user_id','ID de usuario','text'],['course_id','ID de curso','number'],['status','Estado','select',['ACTIVE','COMPLETED','CANCELLED']],['progress_percentage','Avance (%)','number']] },
  certificates: { title:'Certificados', singular:'certificado', service:'academia', path:'certificates', idType:'uuid', fields:[['user_id','ID de usuario','text'],['course_id','ID de curso','number'],['certificate_code','Código','text'],['status','Estado','text']] },
  memberships: { title:'Membresías y becas', singular:'membresía', service:'academia', path:'memberships', idType:'number', fields:[['name','Nombre','text'],['status','Estado','text'],['description','Descripción','textarea']] },
  support: { title:'Soporte', singular:'ticket', service:'academia', path:'support', idType:'number', fields:[['subject','Asunto','text'],['description','Descripción','textarea'],['status','Estado','text'],['priority','Prioridad','text']] },
  materials: { title:'Material educativo', singular:'material', service:'content', path:'materials', idType:'uuid', defaults:{content_type:'MATERIAL',language:'es'}, fields:[['slug','Slug','text'],['title','Título','text'],['description','Descripción','textarea'],['category','Categoría','text'],['content_type','Tipo','select',['MATERIAL','CAPSULE','VIDEO','DOCUMENT','AUDIO','LINK']],['status','Estado','select',['DRAFT','PUBLISHED','ARCHIVED']],['language','Idioma','text'],['cover_url','Portada URL','text']] },
  capsules: { title:'Cápsulas educativas', singular:'cápsula', service:'content', path:'capsules', idType:'number', fields:[['slug','Slug','text'],['title','Título','text'],['summary','Resumen','textarea'],['category','Categoría','text'],['status','Estado','text'],['image','Imagen URL','text']] },
  videos: { title:'Videos', singular:'video', service:'content', path:'videos', idType:'uuid', defaults:{content_type:'VIDEO',language:'es'}, fields:[['slug','Slug','text'],['title','Título','text'],['description','Descripción','textarea'],['status','Estado','select',['DRAFT','PUBLISHED','ARCHIVED']],['duration_seconds','Duración (segundos)','number'],['cover_url','Portada URL','text']] },
  documents: { title:'Documentos', singular:'documento', service:'content', path:'documents', idType:'uuid', defaults:{content_type:'DOCUMENT',language:'es'}, fields:[['slug','Slug','text'],['title','Título','text'],['description','Descripción','textarea'],['status','Estado','select',['DRAFT','PUBLISHED','ARCHIVED']],['cover_url','Portada URL','text']] },
  assistants: { title:'Asistentes IA', singular:'asistente', service:'ai', path:'assistants', idType:'uuid', defaults:{provider:'openai',model:'gpt-4.1-mini',temperature:0.4,is_active:true}, fields:[['name','Nombre','text'],['slug','Slug','text'],['description','Descripción','textarea'],['provider','Proveedor','text'],['model','Modelo','text'],['temperature','Temperatura','number'],['system_instructions','Instrucciones del sistema','textarea'],['is_active','Activo','checkbox']] },
  prompts: { title:'Plantillas de prompts', singular:'prompt', service:'ai', path:'prompts', idType:'uuid', fields:[['name','Nombre','text'],['slug','Slug','text'],['description','Descripción','textarea'],['template','Plantilla','textarea'],['is_active','Activo','checkbox']] },
  chats: { title:'Historial de chats', singular:'chat', service:'ai', path:'chats', idType:'uuid', fields:[['user_id','ID de usuario','text'],['assistant_id','ID de asistente','text'],['title','Título','text'],['status','Estado','text']] },
  rag: { title:'Bases de conocimiento RAG', singular:'base RAG', service:'ai', path:'rag', idType:'uuid', fields:[['name','Nombre','text'],['description','Descripción','textarea'],['qdrant_collection','Colección Qdrant','text'],['status','Estado','text']] },
  users: { title:'Usuarios', singular:'usuario', service:'users', path:'users', idType:'uuid', fields:[['email','Correo','email'],['username','Usuario','text'],['password','Contraseña inicial','password'],['first_name','Nombre','text'],['last_name','Apellidos','text'],['display_name','Nombre visible','text'],['phone','Teléfono','text'],['status','Estado','select',['PENDING','ACTIVE','SUSPENDED','DISABLED']]] },
  roles: { title:'Roles', singular:'rol', service:'users', path:'roles', idType:'uuid', fields:[['code','Código','text'],['name','Nombre','text'],['description','Descripción','textarea'],['is_system','Rol del sistema','checkbox']] },
  permissions: { title:'Permisos', singular:'permiso', service:'users', path:'permissions', idType:'uuid', fields:[['code','Código','text'],['name','Nombre','text'],['description','Descripción','textarea'],['module','Módulo','text']] },
  groups: { title:'Grupos y regiones', singular:'grupo', service:'users', path:'groups', idType:'number', fields:[['name','Nombre','text'],['description','Descripción','textarea'],['status','Estado','text']] },
  notifications: { title:'Notificaciones', singular:'notificación', service:'notifications', path:'notifications', idType:'uuid', fields:[['user_id','ID de usuario','text'],['channel','Canal','select',['EMAIL','WHATSAPP','IN_APP','SMS']],['destination','Destino','text'],['subject','Asunto','text'],['body','Mensaje','textarea'],['status','Estado','select',['PENDING','QUEUED','SENT','DELIVERED','FAILED','CANCELLED']]] },
  templates: { title:'Plantillas', singular:'plantilla', service:'notifications', path:'templates', idType:'uuid', fields:[['name','Nombre','text'],['slug','Slug','text'],['channel','Canal','select',['EMAIL','WHATSAPP','IN_APP','SMS']],['subject_template','Asunto','text'],['body_template','Contenido','textarea'],['is_active','Activa','checkbox']] },
  reminders: { title:'Recordatorios', singular:'recordatorio', service:'notifications', path:'reminders', idType:'uuid', fields:[['user_id','ID de usuario','text'],['title','Título','text'],['message','Mensaje','textarea'],['channel','Canal','text'],['scheduled_at','Programado para','datetime-local'],['status','Estado','text']] },
  scholarshipCodes: { title:'Códigos de beca y correos', singular:'código de beca', service:'users', path:'data/usuarios_codigos_beca_email', idType:'number', fields:[['code','Código','text'],['allowed_email','Correo asignado','email'],['nivel_membresia_id','Nivel de beca','select',['6','8','11']],['max_usos','Usos permitidos','number'],['vigente_desde','Vigente desde','date'],['vigente_hasta','Vigente hasta','date'],['usos_historicos','Usos registrados','number']] },
  scholarships: { title:'Becas registradas', singular:'registro de beca', service:'users', path:'data/usuarios_becas', idType:'number', fields:[['becas_correo','Correo','email'],['rfc','RFC','text'],['beca_id','ID de beca','number'],['total_becas_aprobadas','Becas aprobadas','number'],['total_convocatorias','Convocatorias','number'],['total_convocatorias_activas','Convocatorias activas','number'],['rfc_status','Estado RFC','text'],['historial_completo','Historial completo','checkbox']] },
  pendingActivations: { title:'Activaciones pendientes', singular:'activación pendiente', service:'users', path:'data/usuarios_pendientes', idType:'number', fields:[['usuario','Usuario','text'],['correo','Correo','email'],['estatus','Estado','select',['pendiente','activado','cancelado','error']],['origen','Origen','text'],['rfc','RFC','text'],['region_nombre','Región','text'],['municipio','Municipio','text'],['validacion_mensaje','Mensaje de validación','textarea']] },
  supportTickets: { title:'Peticiones de soporte', singular:'petición', service:'notifications', path:'data/notificaciones_soporte_tickets', idType:'number', fields:[['folio','Folio','text'],['asunto','Asunto','text'],['estado','Estado','select',['nuevo','en_proceso','resuelto','cerrado']],['prioridad','Prioridad','select',['baja','normal','alta','urgente']],['nombre','Solicitante','text'],['correo','Correo','email'],['tema','Tema','text'],['descripcion','Descripción','textarea'],['respuesta_admin','Respuesta administrativa','textarea']] },
  assistantLinks: { title:'Enlaces de asistentes y tutores', singular:'asistente o tutor', service:'ai', path:'data/ia_asistentes_tutores', idType:'number', fields:[['slug','Slug','text'],['numero','Número / orden','text'],['gpt_url','Enlace GPT','text'],['gem_url','Enlace Gemini','text'],['media_id','ID de imagen','number'],['source_option','Sección de origen','text']] },
};
